# permissions for end users to edit mongoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongo-editor-role
rules:
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - mongoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - mongoes/status
  verbs:
  - get
