---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - mongoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - mongoes/finalizers
  verbs:
  - update
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - mongoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongo.alongparty.cn
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
